[package]
name = "gpu-stress-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tch = "0.13"        # PyTorch bindings for Rust
rayon = "1.8"       # Easy multithreading
